name: Manual Release to npm with yarn (trusted)

on:
  workflow_dispatch:
    

permissions:
  contents: write   # нужно для пуша коммита/тега (и для релиза, если добавите)
  id-token: write   # нужно для Trusted Publishing (provenance OIDC)

concurrency:
  group: manual-release
  cancel-in-progress: false

jobs:
  release:
    environment: npm_trusted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm (OIDC)
        run: npm i -g npm@latest

      - run: yarn install 

      - name: Semantic Release (OIDC, без NPM_TOKEN)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: yarn semantic-release
