name: Manual Release to npm with yarn (trusted)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Тип релиза (npm version)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
          - exact
        default: patch
      version:
        description: "Точная версия (для release_type=exact, например 1.2.3)"
        required: false
        type: string
      preid:
        description: "Пререлизный идентификатор (для pre* типов, напр. rc, beta, alpha)"
        required: false
        type: string
        default: rc

permissions:
  contents: write   # нужно для пуша коммита/тега (и для релиза, если добавите)
  id-token: write   # нужно для Trusted Publishing (provenance OIDC)

concurrency:
  group: manual-release
  cancel-in-progress: false

jobs:
  release:
    environment: npm_trusted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm (OIDC)
        run: npm i -g npm@latest

      - run: yarn install --frozen-lockfile

      - name: Semantic Release (OIDC, без NPM_TOKEN)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: yarn semantic-release
