name: Manual Release to npm (trusted)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Тип релиза (npm version)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
          - exact
        default: patch
      version:
        description: "Точная версия (для release_type=exact, например 1.2.3)"
        required: false
        type: string
      preid:
        description: "Пререлизный идентификатор (для pre* типов, напр. rc, beta, alpha)"
        required: false
        type: string
        default: rc

permissions:
  id-token: write   # npm provenance (OIDC)


jobs:
  release:
    environment: npm_trust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужны теги и история
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present


      - name: Publish to npm
        run: |
          # --access public: оставьте, если пакет публичный; уберите для приватного
          npm publish --access public --provenance --tag "${{ github.event.inputs.version }}"
